version: 2

sources:
  - name: northwind_erp
    tables:
      - name: order
        description: tabela de clientes
        columns:
          - name: order_id
            description: primary key
            tests:
              - unique
              - not null

      - name: customers
        description: tabela de clientes

      - name: products
        description: tabela de produtos
        
      - name: shippers
        description: tabela de transportadores
        
      - name: suppliers
        description: tabela de fornecedores
        
      - name: employees
        description: tabela de empregados
