version: 2

sources:
  - name: northwind_erp
    tables:
      - name: order
      - name: customers
      description: tabela de clientes
        columns:
          - name: customer_id
            description: id do cliente
            tests:
              - unique
              - not_null